# Generated by Django 5.2.6 on 2025-10-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
