# Generated by Django 5.2.6 on 2025-10-27 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0002_alter_owner_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='email',
        ),
        migrations.AddField(
            model_name='owner',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parkingpass',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='parkingpass',
            name='pass_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10),
        ),
        migrations.CreateModel(
            name='ParkingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('fees_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='parking_app.vehicle')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
