# Generated by Django 5.2.6 on 2025-10-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0003_remove_owner_contact_number_remove_owner_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingpass',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
