# Generated by Django 5.2.6 on 2025-10-28 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0004_alter_parkingpass_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingtransaction',
            name='status',
            field=models.CharField(default='Parked', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='parking_app.owner'),
        ),
    ]
