# Generated by Django 5.2.6 on 2025-10-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0005_parkingtransaction_status_alter_vehicle_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='owner',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='parkingtransaction',
            name='status',
            field=models.CharField(choices=[('Parked', 'Parked'), ('Exited', 'Exited')], default='Parked', max_length=10),
        ),
    ]
