# Generated by Django 5.2.6 on 2025-10-29 17:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0006_remove_owner_contact_info_owner_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingtransaction',
            name='entry_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='parkingtransaction',
            name='status',
            field=models.CharField(default='Parked', max_length=20),
        ),
        migrations.AlterField(
            model_name='parkingtransaction',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_app.vehicle'),
        ),
    ]
